name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libudev-dev
      - name: Build (all features)
        run: cargo build --locked --all-features
      - name: Test
        run: cargo test --locked
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Format check
        run: cargo fmt --all -- --check


