name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}   # checkout the released tag

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libudev-dev

      - name: Cargo login
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login "$CARGO_REGISTRY_TOKEN"

      - name: Verify version matches tag
        id: ver
        run: |
          TAG="${GITHUB_REF##*/}"
          TAG_STRIPPED="${TAG#sergw-}"
          TAG_STRIPPED="${TAG_STRIPPED#v}"
          PKG_VER=$(sed -n 's/^version\s*=\s*"\([^"]\+\)"/\1/p' Cargo.toml | head -n1)
          echo "tag=$TAG_STRIPPED" >> $GITHUB_OUTPUT
          echo "pkg=$PKG_VER" >> $GITHUB_OUTPUT
          test "$TAG_STRIPPED" = "$PKG_VER"

      - name: Build (all features)
        run: cargo build --all-features --locked

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --locked


